spring:
  config:
    activate:
      on-profile: dev
  banner:
    location: dev-banner.txt

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234

  data:
    web:
      pageable:
        default-page-size: 20 # Pageable 상속 시 기본값으로 page 20개씩 조회하도록 설정

  servlet:
    multipart:
      max-request-size: 5MB  #업로드 파일 크기 총량 제한
      max-file-size: 2MB     #업로드 파일 크기 제한

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100 #배치 사이즈 (Collection 조회 최적화)

    hibernate:
      ddl-auto: create

    show-sql: true
    open-in-view: false #OSIV 사용하지 않기


logging:
  level:
    p6spy: debug

    org:
      apache:
        coyote:
          http11: debug # HTTP Log On

      hiberante:
        SQL: debug

    boardexample:
      myboard: debug

file:
  dir: /Users/solmin/Desktop/file